# App
spring.application.name=TallerOS

# Base de datos (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/talleros_db
spring.datasource.username=root
spring.datasource.password=tu_password

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT (cambiá el secret en producción)
jwt.secret=talleros_super_secret_key_2024_cambiame
jwt.expiration=86400000

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
